apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-25T14:47:00Z"
  labels:
    app: weqohash-webapp
  name: qserv
  namespace: default
  resourceVersion: "2593"
  selfLink: /api/v1/namespaces/default/services/qserv
  uid: 974578c1-9e96-11ea-b631-02535ab1aff3
spec:
  clusterIP: 172.20.154.136
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30477
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: weqohash-webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a974578c19e9611eab63102535ab1aff-1437146507.us-east-1.elb.amazonaws.com
